### ISSUE TITLE
[Suggestion] Publish to Modrinth/Curseforge

### ISSUE THREAD

**Issue by JustAHuman-xD** [StoneLabs/working-graves#1]
Could you publish this to modrinth or curseforge? It would allow those on free hosts to have a chance at using this and this looks like a great mod!

**Comment by StoneLabs** [comment]
I'll look into modrinth, thanks

**Comment by StoneLabs** [comment]
https://modrinth.com/mod/working-graves

Currently under review.

**Comment by JustAHuman-xD** [comment]
Awesome!
