### ISSUE TITLE
Trinkets

### ISSUE THREAD

**Issue by tacogerbil** [StoneLabs/working-graves#14]
I saw that there were issues with Trinkets in the past and some fix was put in..  Currently on Minecraft 1.19.2 with Fabric Loader 0.14.21 and workinggraves 1.3.0.
When we place "create" goggles in the trinket slot, "icarus" wings and "simple magnets" magnets in their trinket slots.  Upon death they are simply dropped.
Otherwise it's been working wonderfully :)  Thank you so much!  Now if I could just get the kids to create a sign after they use up a grave hehehe 🤣

**Comment by StoneLabs** [comment]
Tested in 1.20.2, works as expected with elytra trinket slot.

Cant reproduce.

**Comment by tacogerbil** [comment]
The issue is on 1.19.2...  not 1.20.2... 🤔

**Comment by StoneLabs** [comment]
My apologies, but I don't want to fix bugs in older versions, too much effort. I'd need to backport the code to 1.19.2 and fix it there.

Sorry :)
