### ISSUE TITLE
Restrict grave creation to ops/creative/something

### ISSUE THREAD

**Issue by hattrickpatrick** [StoneLabs/working-graves#16]
Hello, I love the concept of this mod, most such mods create the 'grave' at the player's location, I love the thought of building a central cemetery somewhere that a player can go to to find their stuff. It's an awesome idea.

For server owners who like I mentioned want to make a central cemetery, tomb, graveyard, etc (so many ideas!) can you add the ability to restrict who can create these graves?

Thankyou!

[edit] I'm not sure how to tag this as a suggestion/feature request, sorry

**Comment by StoneLabs** [comment]
Will be done before the next release, thanks for the idea.

**Comment by StoneLabs** [comment]
Grave creation now requires a permission level at least equal to 'gravesRequiredPermissionLevel' gamerule.
Set it to 1 to only allow Moderators/Admins/OPs etc...
