### ISSUE TITLE
Trinkets compatibility

### ISSUE THREAD

**Issue by SanityCh3ck** [StoneLabs/working-graves#3]
Items in Trinket slots are not put into graves and instead dropped on the ground.

**Comment by StoneLabs** [comment]
What mods are you using for the trinket slots?

**Comment by SanityCh3ck** [comment]
I'm using Backpacked and Bewitchment

**Comment by StoneLabs** [comment]
Alright. I can't promise to fix it soon, but if i find some time i'll look into it.

**Comment by SanityCh3ck** [comment]
Trinkets drops all of its items directly according to its own drop rules via [this code right here](https://github.com/emilyploszaj/trinkets/blob/main/src/main/java/dev/emi/trinkets/mixin/LivingEntityMixin.java).
All other grave mods I looked at had some special handling for Trinkets, so it doesn't seem like any implicit solution without an optional dependency is viable.
